"""initial setup

Revision ID: 32b7859f5445
Revises: 
Create Date: 2026-06-08 13:32:28.857189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b7859f5445'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_social', sa.Boolean(), nullable=True),
    sa.Column('social_provider', sa.String(), nullable=True),
    sa.Column('social_id', sa.String(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('presentation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('practice_count', sa.Integer(), nullable=True),
    sa.Column('user_nickname', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_critique', sa.Text(), nullable=True),
    sa.Column('persona_questions', sa.JSON(), nullable=True),
    sa.Column('strength', sa.JSON(), nullable=True),
    sa.Column('weakness', sa.JSON(), nullable=True),
    sa.Column('improvement', sa.JSON(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('delivery_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('stt_result', sa.Text(), nullable=True),
    sa.Column('voice_analysis', sa.JSON(), nullable=True),
    sa.Column('visual_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_records_id'), 'presentation_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presentation_records_id'), table_name='presentation_records')
    op.drop_table('presentation_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
